# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zero_3ez.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import*

import winsound
#winsound.PlaySound('5',winsound.SND_ASYNC)
import playsound
from PyQt5 import QtCore as qtc
from PyQt5 import QtWidgets as qtw
import pyqtgraph as pg
from scipy.io import wavfile
import numpy as np
import sounddevice as sd
from scipy import signal
import matplotlib.pyplot as plt
import math
import vlc


import os
import sys

sample_rate = 0
counter = 0
data = []
raw_data = []
aux_data = []

import sourceGuitar

import pygame

#from tkinter import *
  
# import filedialog module
from tkinter import filedialog




class Ui_Piano_istrument(object):
    def setupUi(self, Piano_istrument):
        Piano_istrument.setObjectName("Piano_istrument")
        Piano_istrument.resize(1206, 879)
        Piano_istrument.setStyleSheet("#Piano_Button_1,#Piano_Button_2,#Piano_Button_3,#Piano_Button_4,#Piano_Button_5,#Piano_Button_6,#Piano_Button_7\n"
"{\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"#Piano_Button_1:hover,#Piano_Button_2:hover,#Piano_Button_3:hover,#Piano_Button_4:hover,#Piano_Button_5:hover,#Piano_Button_6:hover,#Piano_Button_7:hover\n"
"{\n"
"background-color: rgb(240, 240, 250);\n"
"}\n"
"\n"
"#Piano_Button_1:pushed,#Piano_Button_2:pushed,#Piano_Button_3:pushed,#Piano_Button_4:pushed,#Piano_Button_5:pushed,#Piano_Button_6:pushed,#Piano_Button_7:pushed\n"
"{\n"
"background-color: rgb(255, 255, 0)\n"
"}\n"
"\n"
"#Piano_Button_above_1,#Piano_Button_above_2,#Piano_Button_above_3,#Piano_Button_above_4,#Piano_Button_above_5\n"
"{\n"
"background-color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"#Piano_Button_above_1:hover,#Piano_Button_above_2:hover,#Piano_Button_above_3:hover,#Piano_Button_above_4:hover,#Piano_Button_above_5:hover,DrumbButton:hover\n"
"{\n"
"background-color: rgb(75, 75, 75);\n"
"}\n"
"#Piano_Button_above_1:pushed,#Piano_Button_above_2:pushed,#Piano_Button_above_3:pushed,#Piano_Button_above_4:pushed,#Piano_Button_above_5:pushed,DrumbButton:pushed\n"
"{\n"
"background-color: rgb(50, 50, 50);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Piano_istrument)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgets = QtWidgets.QTabWidget(Piano_istrument)
        self.tabWidgets.setObjectName("tabWidgets")
        self.musicTab = QtWidgets.QWidget()
        self.musicTab.setWhatsThis("")
        self.musicTab.setObjectName("musicTab")
        self.frameForPiano = QtWidgets.QFrame(self.musicTab)
        self.frameForPiano.setGeometry(QtCore.QRect(40, 50, 371, 211))
        self.frameForPiano.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForPiano.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameForPiano.setObjectName("frameForPiano")
        self.gridLayout = QtWidgets.QGridLayout(self.frameForPiano)
        self.gridLayout.setObjectName("gridLayout")
        self.backGroundForPiano = QtWidgets.QLabel(self.frameForPiano)
        self.backGroundForPiano.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(148, 118, 254, 255), stop:1 rgba(71, 255, 243, 255))")
        self.backGroundForPiano.setText("")
        self.backGroundForPiano.setObjectName("backGroundForPiano")
        self.gridLayout.addWidget(self.backGroundForPiano, 0, 0, 1, 1)
        self.backGroundForSubPiano = QtWidgets.QLabel(self.frameForPiano)
        self.backGroundForSubPiano.setGeometry(QtCore.QRect(10, 10, 351, 61))
        self.backGroundForSubPiano.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.backGroundForSubPiano.setText("")
        self.backGroundForSubPiano.setObjectName("backGroundForSubPiano")
        self.Piano_Button_above_4 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_above_4.setGeometry(QtCore.QRect(240, 30, 40, 130))
        self.Piano_Button_above_4.setText("")
        self.Piano_Button_above_4.setObjectName("Piano_Button_above_4")
        self.Piano_Button_6 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_6.setGeometry(QtCore.QRect(260, 70, 50, 130))
        self.Piano_Button_6.setText("")
        self.Piano_Button_6.setObjectName("Piano_Button_6")
        self.Piano_Button_above_5 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_above_5.setGeometry(QtCore.QRect(290, 30, 40, 130))
        self.Piano_Button_above_5.setText("")
        self.Piano_Button_above_5.setObjectName("Piano_Button_above_5")
        self.Piano_Button_4 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_4.setGeometry(QtCore.QRect(160, 70, 50, 130))
        self.Piano_Button_4.setText("")
        self.Piano_Button_4.setObjectName("Piano_Button_4")
        self.Piano_Button_7 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_7.setGeometry(QtCore.QRect(310, 70, 50, 130))
        self.Piano_Button_7.setText("")
        self.Piano_Button_7.setObjectName("Piano_Button_7")
        self.Piano_Button_above_1 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_above_1.setGeometry(QtCore.QRect(40, 30, 40, 130))
        self.Piano_Button_above_1.setText("")
        self.Piano_Button_above_1.setObjectName("Piano_Button_above_1")
        self.Piano_Button_above_3 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_above_3.setGeometry(QtCore.QRect(190, 30, 40, 130))
        self.Piano_Button_above_3.setText("")
        self.Piano_Button_above_3.setObjectName("Piano_Button_above_3")
        self.Piano_Button_1 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_1.setGeometry(QtCore.QRect(10, 70, 50, 130))
        self.Piano_Button_1.setText("")
        self.Piano_Button_1.setObjectName("Piano_Button_1")
        self.Piano_Button_2 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_2.setGeometry(QtCore.QRect(60, 70, 50, 130))
        self.Piano_Button_2.setText("")
        self.Piano_Button_2.setObjectName("Piano_Button_2")
        self.Piano_Button_3 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_3.setGeometry(QtCore.QRect(110, 70, 50, 130))
        self.Piano_Button_3.setText("")
        self.Piano_Button_3.setObjectName("Piano_Button_3")
        self.Piano_Button_5 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_5.setGeometry(QtCore.QRect(210, 70, 50, 130))
        self.Piano_Button_5.setText("")
        self.Piano_Button_5.setObjectName("Piano_Button_5")
        self.Piano_Button_above_2 = QtWidgets.QPushButton(self.frameForPiano)
        self.Piano_Button_above_2.setGeometry(QtCore.QRect(90, 30, 40, 130))
        self.Piano_Button_above_2.setText("")
        self.Piano_Button_above_2.setObjectName("Piano_Button_above_2")
        self.backGroundForPiano.raise_()
        self.Piano_Button_6.raise_()
        self.Piano_Button_4.raise_()
        self.Piano_Button_7.raise_()
        self.Piano_Button_1.raise_()
        self.Piano_Button_2.raise_()
        self.Piano_Button_3.raise_()
        self.Piano_Button_5.raise_()
        self.Piano_Button_above_4.raise_()
        self.Piano_Button_above_5.raise_()
        self.Piano_Button_above_1.raise_()
        self.Piano_Button_above_2.raise_()
        self.Piano_Button_above_3.raise_()
        self.backGroundForSubPiano.raise_()
        self.Guitar_widget = QtWidgets.QWidget(self.musicTab)
        self.Guitar_widget.setGeometry(QtCore.QRect(50, 300, 951, 501))
        self.Guitar_widget.setObjectName("Guitar_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Guitar_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Guitar_Picture = QtWidgets.QLabel(self.Guitar_widget)
        self.Guitar_Picture.setStyleSheet("image: url(:/newPrefix/Guitar.png);")
        self.Guitar_Picture.setText("")
        self.Guitar_Picture.setObjectName("Guitar_Picture")
        self.gridLayout_4.addWidget(self.Guitar_Picture, 0, 0, 1, 1)
        self.Guitar_button_4 = QtWidgets.QPushButton(self.Guitar_widget)
        self.Guitar_button_4.setGeometry(QtCore.QRect(240, 280, 16, 16))
        self.Guitar_button_4.setText("")
        self.Guitar_button_4.setObjectName("Guitar_button_4")
        self.Guitar_button_1 = QtWidgets.QPushButton(self.Guitar_widget)
        self.Guitar_button_1.setGeometry(QtCore.QRect(180, 250, 16, 16))
        self.Guitar_button_1.setText("")
        self.Guitar_button_1.setObjectName("Guitar_button_1")
        self.Guitar_button_2 = QtWidgets.QPushButton(self.Guitar_widget)
        self.Guitar_button_2.setGeometry(QtCore.QRect(200, 260, 16, 16))
        self.Guitar_button_2.setText("")
        self.Guitar_button_2.setObjectName("Guitar_button_2")
        self.Guitar_button_3 = QtWidgets.QPushButton(self.Guitar_widget)
        self.Guitar_button_3.setGeometry(QtCore.QRect(220, 270, 16, 16))
        self.Guitar_button_3.setText("")
        self.Guitar_button_3.setObjectName("Guitar_button_3")
        self.Guitar_button_5 = QtWidgets.QPushButton(self.Guitar_widget)
        self.Guitar_button_5.setGeometry(QtCore.QRect(260, 290, 16, 16))
        self.Guitar_button_5.setText("")
        self.Guitar_button_5.setObjectName("Guitar_button_5")
        self.Guitar_button_5.raise_()
        self.Guitar_Picture.raise_()
        self.Guitar_button_4.raise_()
        self.Guitar_button_1.raise_()
        self.Guitar_button_2.raise_()
        self.Guitar_button_3.raise_()
        self.widget = QtWidgets.QWidget(self.musicTab)
        self.widget.setGeometry(QtCore.QRect(580, 40, 401, 261))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_5.addWidget(self.pushButton_14, 1, 3, 1, 1)
        self.horizontalSlider_For_piano = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_For_piano.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_For_piano.setObjectName("horizontalSlider_For_piano")
        self.gridLayout_5.addWidget(self.horizontalSlider_For_piano, 4, 0, 1, 3)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 0, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 1, 0, 1, 2)
        self.horizontalSlider_For_Drumb = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_For_Drumb.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_For_Drumb.setObjectName("horizontalSlider_For_Drumb")
        self.gridLayout_5.addWidget(self.horizontalSlider_For_Drumb, 2, 0, 1, 3)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 0, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_5.addWidget(self.pushButton_13, 1, 2, 1, 1)
        self.horizontalSlider_For_Guitar = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_For_Guitar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_For_Guitar.setObjectName("horizontalSlider_For_Guitar")
        self.gridLayout_5.addWidget(self.horizontalSlider_For_Guitar, 3, 0, 1, 3)
        self.comboBox_for_tunes = QtWidgets.QComboBox(self.widget)
        self.comboBox_for_tunes.setObjectName("comboBox_for_tunes")
        self.comboBox_for_tunes.addItem("")
        self.comboBox_for_tunes.addItem("")
        self.comboBox_for_tunes.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_for_tunes, 2, 3, 1, 1)
        self.DrumbButton = QtWidgets.QPushButton(self.musicTab)
        self.DrumbButton.setGeometry(QtCore.QRect(440, 90, 111, 111))
        self.DrumbButton.setStyleSheet("#DrumbButton {\n"
"    \n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 50px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"#DrumbButton:hover {\n"
"background:qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}\n"
"\n"
"#DrumbButton:pushed\n"
"{\n"
"background:qradialgradient(\n"
"cx: 0.8, cy: -0.9, fx: 0.3, fy: -0.5,\n"
"radius: 1.5, stop: 1 #000, stop: 2 #aaa\n"
");\n"
"}\n"
"")
        self.DrumbButton.setText("")
        self.DrumbButton.setObjectName("DrumbButton")
        self.tabWidgets.addTab(self.musicTab, "")
        self.equilizerTab = QtWidgets.QWidget()
        self.equilizerTab.setObjectName("equilizerTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.equilizerTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_Play = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_Play.setObjectName("pushButton_Play")
        self.gridLayout_3.addWidget(self.pushButton_Play, 2, 0, 1, 1)
        self.pushButton_Open = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.gridLayout_3.addWidget(self.pushButton_Open, 1, 0, 1, 1)
        self.Guitar_Picture_5 = QtWidgets.QLabel(self.equilizerTab)
        self.Guitar_Picture_5.setStyleSheet("image: url(:/newPrefix/drumb.png);\n"
"")
        self.Guitar_Picture_5.setText("")
        self.Guitar_Picture_5.setObjectName("Guitar_Picture_5")
        self.gridLayout_3.addWidget(self.Guitar_Picture_5, 1, 1, 4, 1)
        self.pushButton_pause = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.gridLayout_3.addWidget(self.pushButton_pause, 3, 0, 1, 1)
        self.horizontalSlider_For_Drumb_2 = QtWidgets.QSlider(self.equilizerTab)
        self.horizontalSlider_For_Drumb_2.setMaximum(10)
        self.horizontalSlider_For_Drumb_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_For_Drumb_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_For_Drumb_2.setObjectName("horizontalSlider_For_Drumb_2")
        self.gridLayout_3.addWidget(self.horizontalSlider_For_Drumb_2, 7, 1, 2, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 6, 0, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 4, 0, 2, 1)
        self.Guitar_Picture_4 = QtWidgets.QLabel(self.equilizerTab)
        self.Guitar_Picture_4.setStyleSheet("\n"
"image: url(:/newPrefix/piano2.png);")
        self.Guitar_Picture_4.setText("")
        self.Guitar_Picture_4.setObjectName("Guitar_Picture_4")
        self.gridLayout_3.addWidget(self.Guitar_Picture_4, 2, 2, 4, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.equilizerTab)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 8, 0, 1, 1)
        self.signal_Plot_widget = QtWidgets.QOpenGLWidget(self.equilizerTab)
        self.signal_Plot_widget.setObjectName("signal_Plot_widget")
        self.gridLayout_3.addWidget(self.signal_Plot_widget, 0, 0, 1, 2)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.equilizerTab)
        self.horizontalSlider_6.setMaximum(10)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.gridLayout_3.addWidget(self.horizontalSlider_6, 8, 3, 1, 1)
        self.Guitar_Picture_2 = QtWidgets.QLabel(self.equilizerTab)
        self.Guitar_Picture_2.setStyleSheet("image: url(:/newPrefix/Guitar.png);")
        self.Guitar_Picture_2.setText("")
        self.Guitar_Picture_2.setObjectName("Guitar_Picture_2")
        self.gridLayout_3.addWidget(self.Guitar_Picture_2, 2, 3, 4, 1)
        self.verticalSlider_For_volume_control = QtWidgets.QSlider(self.equilizerTab)
        self.verticalSlider_For_volume_control.setSliderPosition(10)
        self.verticalSlider_For_volume_control.setMaximum(10)
        self.verticalSlider_For_volume_control.setPageStep(1)
        self.verticalSlider_For_volume_control.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_For_volume_control.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_For_volume_control.setObjectName("verticalSlider_For_volume_control")
        self.gridLayout_3.addWidget(self.verticalSlider_For_volume_control, 0, 4, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.equilizerTab)
        self.horizontalSlider_5.setMaximum(10)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout_3.addWidget(self.horizontalSlider_5, 8, 2, 1, 1)
        self.SpectroGram_widget = QtWidgets.QGraphicsView(self.equilizerTab)
        self.SpectroGram_widget.setObjectName("SpectroGram_widget")
        self.gridLayout_3.addWidget(self.SpectroGram_widget, 0, 3, 1, 1)
        self.tabWidgets.addTab(self.equilizerTab, "")
        self.verticalLayout.addWidget(self.tabWidgets)

        self.retranslateUi(Piano_istrument)
        self.tabWidgets.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Piano_istrument)
        
        
        self.Piano_Button_1.clicked.connect(self.pb1)
        self.Piano_Button_2.clicked.connect(self.pb2)
        self.Piano_Button_3.clicked.connect(self.pb3)
        self.Piano_Button_4.clicked.connect(self.pb4)
        self.Piano_Button_5.clicked.connect(self.pb5)
        self.Piano_Button_6.clicked.connect(self.pb6)
        self.Piano_Button_7.clicked.connect(self.pb7)
        self.Piano_Button_above_1.clicked.connect(self.pb8)
        self.Piano_Button_above_2.clicked.connect(self.pb9)
        self.Piano_Button_above_3.clicked.connect(self.pb10)
        self.Piano_Button_above_4.clicked.connect(self.pb11)
        self.Piano_Button_above_5.clicked.connect(self.pb12)
        self.DrumbButton.clicked.connect(self.pb0)
        self.pushButton_Open.clicked.connect(self.openWaveFile)
        self.pushButton_pause.clicked.connect(self.stop_media)
        self.pushButton_Play.clicked.connect(self.play_media)
        self.verticalSlider_For_volume_control.valueChanged.connect(self.Volume_Control)
        

        self.signal_viewer_widget = pg.PlotWidget()
        pen = pg.mkPen(color=(0, 0, 255))
        self.graph = self.signal_viewer_widget.plot([], [], pen=pen)



    def openWaveFile(self):
        #file_name= qtw.QFileDialog.getOpenFileName(None, 'Open mp3', QtCore.QDir.rootPath(), 'mp3(*.mp3)')
#        self.sample_rate, self.raw_data = wavfile.read(file_name)
        pass
        #Ammar

        # filename = filedialog.askopenfilename(initialdir = "/",
        #                                   title = "Select a File",
        #                                   filetypes = (("Text files",
        #                                                 "*.mp3"),
        #                                                ("all files",
        #                                                 "*.*")))
        # pygame.mixer.music.load(filename)
        
        
        # length = self.raw_data.shape[0] / self.sample_rate
        # self.time = np.linspace(0., length, self.raw_data.shape[0])
        # self.data = self.raw_data[:, 0] / 2 ** 15  # to normalize data
        # self.signal_viewer_widget.setYRange(min(self.data), max(self.data))
        
        

    def pb0(self):
        winsound.Beep(175,600)   ##Drum
    def pb1(self):
         winsound.Beep(871,980)
    def pb2(self):
         winsound.Beep(821,870)
    def pb3(self):
         winsound.Beep(731,820)
    def pb4(self):
         winsound.Beep(650,730)
    def pb5(self):
         winsound.Beep(611,650)
    def pb6(self):
         winsound.Beep(581,611)
    def pb7(self):
        winsound.Beep(550,580)
    def pb8(self):
         winsound.Beep(1030,1160)
    def pb9(self):
         winsound.Beep(920,1030)
    def pb10(self):
         winsound.Beep(770,920)
    def pb11(self):
        winsound.Beep(690,770)
    def pb12(self):
         winsound.Beep(580,690)

    def stop_media(self):
         pygame.mixer.music.pause()
         
    def play_media(self):
        pygame.mixer.music.unpause()
        
    def Volume_Control(self):
        volume_Value = float(self.verticalSlider_For_volume_control.value())
        pygame.mixer.music.set_volume(volume_Value*0.1)

    def retranslateUi(self, Piano_istrument):
        _translate = QtCore.QCoreApplication.translate
        Piano_istrument.setWindowTitle(_translate("Piano_istrument", "Form"))
        self.tabWidgets.setWhatsThis(_translate("Piano_istrument", "<html><head/><body><p>musicTab</p></body></html>"))
        self.pushButton_14.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_10.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_12.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_11.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_13.setText(_translate("Piano_istrument", "PushButton"))
        self.comboBox_for_tunes.setItemText(0, _translate("Piano_istrument", "octave"))
        self.comboBox_for_tunes.setItemText(1, _translate("Piano_istrument", "solo"))
        self.comboBox_for_tunes.setItemText(2, _translate("Piano_istrument", "spare"))
        self.tabWidgets.setTabText(self.tabWidgets.indexOf(self.musicTab), _translate("Piano_istrument", "musicTab"))
        self.pushButton_Play.setText(_translate("Piano_istrument", "Play"))
        self.pushButton_Open.setText(_translate("Piano_istrument", "Open"))
        self.pushButton_pause.setText(_translate("Piano_istrument", "Pause"))
        self.pushButton_3.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_2.setText(_translate("Piano_istrument", "PushButton"))
        self.pushButton_8.setText(_translate("Piano_istrument", "PushButton"))
        self.tabWidgets.setTabText(self.tabWidgets.indexOf(self.equilizerTab), _translate("Piano_istrument", "equilizerTab"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Piano_istrument = QtWidgets.QWidget()
    ui = Ui_Piano_istrument()
    ui.setupUi(Piano_istrument)
    # p = vlc.MediaPlayer("2.mp3")
    # p.play()
    file = '2.mp3'
    pygame.init()
    pygame.mixer.init()
    pygame.mixer.music.load(file)
    pygame.mixer.music.play()
    
    Piano_istrument.show()
    
    sys.exit(app.exec_())
